CREATE DATABASE IF NOT EXISTS casita_libros;

USE casita_libros;

CREATE TABLE tipo_libro(
id_tipo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
tipo VARCHAR(15) NOT NULL
)ENGINE INNODB;

CREATE TABLE libros(
id_libro INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
titulo VARCHAR(50) NOT NULL,
autores VARCHAR(50) NOT NULL,
id_tipo INT NOT NULL,
CONSTRAINT FOREIGN KEY (id_tipo) REFERENCES tipo_libro(id_tipo) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE INNODB;
